"""
Record the README demo GIF by actually driving the console.

    python scripts/record_demo.py                       # record the deployed site
    python scripts/record_demo.py --url http://localhost:5173
    python scripts/record_demo.py --scenario escalation --out docs/demo-escalation.gif

The GIF is generated, not hand-recorded with a screen capture tool. That matters for a
boring reason: when the console changes, the demo can be regenerated by running this
again, instead of quietly going stale and showing a UI that no longer exists.

It drives Replay mode, which plays a baked run in the browser. No API key, no tokens, no
provider that can rate-limit halfway through a recording.

Requirements (dev only, not in requirements.txt):
    pip install playwright pillow
    python -m playwright install chromium
"""
from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import time
from pathlib import Path

# The console renders box-drawing and arrow glyphs, and Playwright echoes page text on a
# failure. A Windows console in a non-UTF-8 locale dies on those with a UnicodeEncodeError
# that looks like a Playwright bug and is not one.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):
    pass

REPO = Path(__file__).resolve().parents[1]
DEFAULT_URL = "https://ma731.github.io/titan-operations-sentinel/"
DEFAULT_OUT = REPO / "docs" / "demo.gif"

# The replay stream is about 39 seconds of trace events plus the approval gate. Capturing
# at 0.7s and playing back at the same interval keeps the GIF in real time at roughly 75
# seconds, which is the length a reader will actually sit through.
FRAME_INTERVAL_S = 0.7


def _shot(page, frames_dir: Path, counter: list[int], stamps: list[float]) -> None:
    counter[0] += 1
    page.screenshot(path=str(frames_dir / f"f{counter[0]:04d}.png"))
    stamps.append(time.monotonic())


def _capture_for(page, seconds: float, frames_dir: Path, counter: list[int],
                 stamps: list[float], stop_when=None) -> bool:
    """Screenshot every FRAME_INTERVAL_S for `seconds`. Returns True if stop_when fired.

    Each frame's capture time is recorded, because taking a screenshot is not free: it
    costs a couple of hundred milliseconds, so frames land further apart than the nominal
    interval. Playing them back at a fixed interval would make the GIF run noticeably
    faster than the thing it is a recording of. _assemble uses the real gaps instead.

    `stop_when` lets the run advance as soon as the UI reaches a state (the approval
    modal, the final plan) rather than sleeping for a guessed duration, so the recording
    stays in sync with the app if its timings change."""
    deadline = time.monotonic() + seconds
    while time.monotonic() < deadline:
        _shot(page, frames_dir, counter, stamps)
        if stop_when is not None and stop_when():
            return True
        time.sleep(FRAME_INTERVAL_S)
    return False


def _click(page, selector: str, timeout_ms: int = 15000) -> None:
    page.wait_for_selector(selector, timeout=timeout_ms)
    page.click(selector)


def record(url: str, out: Path, scenario: str, width: int, height: int,
           colors: int, scale: float, keep_frames: bool) -> Path:
    from playwright.sync_api import sync_playwright

    frames_dir = Path(tempfile.mkdtemp(prefix="tos-demo-"))
    counter = [0]
    stamps: list[float] = []
    print(f"Recording {url}\n  frames -> {frames_dir}")

    with sync_playwright() as p:
        browser = p.chromium.launch()
        page = browser.new_page(viewport={"width": width, "height": height},
                                device_scale_factor=1)
        page.goto(url, wait_until="networkidle", timeout=60000)

        # 1. Sign-in splash. The recording enters as a guest rather than as a named
        #    teammate, so the GIF does not put one person's face on a group project.
        page.wait_for_timeout(1200)
        _capture_for(page, 2.0, frames_dir, counter, stamps)
        _click(page, ".si-skip")
        page.wait_for_timeout(1500)

        # 2. Showcase. A short beat on the hero, then straight into the console: the
        #    reader came to see the agents run, not to read a landing page.
        _capture_for(page, 3.5, frames_dir, counter, stamps)
        _click(page, ".sc-cta, .sc-btn-primary")
        page.wait_for_timeout(1500)

        # 3. Console. A first-visit coachmark can be covering the controls.
        page.wait_for_timeout(1200)
        if page.locator(".coach-go").count():
            _capture_for(page, 2.0, frames_dir, counter, stamps)
            page.click(".coach-go")
            page.wait_for_timeout(600)

        _capture_for(page, 2.5, frames_dir, counter, stamps)
        if scenario != "happy":
            label = {"edge": "Edge", "escalation": "Escalation"}[scenario]
            page.click(f".dash-tab:has-text('{label}')")
            page.wait_for_timeout(700)
            _capture_for(page, 1.5, frames_dir, counter, stamps)

        _click(page, "button.go")

        # 4. The run itself. Stop as soon as the approval modal appears rather than
        #    sleeping for a fixed guess.
        gate = _capture_for(
            page, 90.0, frames_dir, counter, stamps,
            stop_when=lambda: page.locator(".btn.approve").count() > 0,
        )

        # 5. The human gate. Hold on it: this is the single most important frame in the
        #    whole recording, because it is the thing that separates this from a demo
        #    that just prints a plan.
        if gate:
            print("  approval gate reached")
            _capture_for(page, 5.0, frames_dir, counter, stamps)
            _click(page, ".btn.approve")
            page.wait_for_timeout(800)
        else:
            print("  no approval gate on this path (expected on the escalation scenario)")

        # 6. Land on the payoff. The dashboard goes back to idle once the run ends, which
        #    is an anticlimax to end a recording on, so switch to the Action Plan view and
        #    hold there: the tiered AUTO / APPROVE / MONITOR output is the thing the whole
        #    run exists to produce.
        _capture_for(page, 4.0, frames_dir, counter, stamps)
        plan_tab = page.locator(".nav-item:has-text('Action Plan')")
        if plan_tab.count():
            plan_tab.first.click()
            page.wait_for_timeout(900)
        _capture_for(page, 16.0, frames_dir, counter, stamps)

        browser.close()

    print(f"  captured {counter[0]} frames")
    gif = _assemble(frames_dir, out, stamps, colors=colors, scale=scale)
    if not keep_frames:
        shutil.rmtree(frames_dir, ignore_errors=True)
    return gif


def _assemble(frames_dir: Path, out: Path, stamps: list[float],
              colors: int, scale: float) -> Path:
    """Build the GIF.

    Two things keep the file small enough for a README. Every frame is quantised against
    ONE shared palette built from the middle of the run, which stops the encoder storing
    a new local colour table per frame; and identical consecutive frames are dropped and
    their time folded into the previous frame's duration, which matters here because the
    console is static between trace events."""
    from PIL import Image

    paths = sorted(frames_dir.glob("f*.png"))
    if not paths:
        raise SystemExit("no frames captured")

    target = None
    frames, durations = [], []
    palette_source = Image.open(paths[len(paths) // 2]).convert("RGB")
    if scale != 1.0:
        palette_source = palette_source.resize(
            (int(palette_source.width * scale), int(palette_source.height * scale)),
            Image.LANCZOS)
    palette = palette_source.quantize(colors=colors, method=Image.MEDIANCUT)

    # Real gap between consecutive captures, so the GIF plays at the speed the console
    # actually ran. Clamped: a stall while the browser did layout work should not become
    # a five second freeze in the recording.
    gaps = [max(120, min(2500, int((b - a) * 1000)))
            for a, b in zip(stamps, stamps[1:], strict=False)]
    gaps.append(1800)                       # hold the last frame before the loop restarts

    previous_bytes = None
    for i, path in enumerate(paths):
        step_ms = gaps[i] if i < len(gaps) else 700
        img = Image.open(path).convert("RGB")
        if scale != 1.0:
            target = target or (int(img.width * scale), int(img.height * scale))
            img = img.resize(target, Image.LANCZOS)
        quantised = img.quantize(palette=palette, dither=Image.FLOYDSTEINBERG)
        raw = quantised.tobytes()
        if raw == previous_bytes and durations:
            durations[-1] += step_ms          # hold the frame instead of storing it twice
            continue
        previous_bytes = raw
        frames.append(quantised)
        durations.append(step_ms)

    out.parent.mkdir(parents=True, exist_ok=True)
    frames[0].save(out, save_all=True, append_images=frames[1:], loop=0,
                   duration=durations, optimize=True, disposal=1)
    size_mb = out.stat().st_size / 1_000_000
    total_s = sum(durations) / 1000
    print(f"  {len(frames)} unique frames, {total_s:.0f}s playback, {size_mb:.1f} MB")
    if not 55 <= total_s <= 95:
        print(f"  NOTE: {total_s:.0f}s is outside the 60-90s the README wants. "
              "Adjust the hold durations in record().")
    print(f"  wrote {out}")
    if size_mb > 10:
        print("  WARNING: over 10 MB. Lower --colors or --scale before committing it.")
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Record the console demo as a GIF.")
    ap.add_argument("--url", default=DEFAULT_URL)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--scenario", default="happy", choices=["happy", "edge", "escalation"])
    ap.add_argument("--width", type=int, default=1280)
    ap.add_argument("--height", type=int, default=760)
    ap.add_argument("--scale", type=float, default=0.72,
                    help="downscale factor applied to every frame (file size vs sharpness)")
    ap.add_argument("--colors", type=int, default=96,
                    help="shared palette size; the console is a dark UI and needs few")
    ap.add_argument("--keep-frames", action="store_true")
    args = ap.parse_args(argv)

    try:
        record(args.url, args.out, args.scenario, args.width, args.height,
               args.colors, args.scale, args.keep_frames)
    except ImportError as exc:
        print(f"Missing a dev dependency ({exc}).\n"
              "  pip install playwright pillow\n"
              "  python -m playwright install chromium")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
